### ISSUE TITLE
add data list into input on custom block

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2773] opened 2021-02-05 14:22 UTC
Hi,
i have one suggestion with 2 screenshot
![Sans titre](https://user-images.githubusercontent.com/5407223/107045587-f6b1d580-67c5-11eb-9ff8-5a9f03cc18e4.png)
![Capture](https://user-images.githubusercontent.com/5407223/107045600-fa455c80-67c5-11eb-8644-c23f5240b283.PNG)

**Comment by bromagosa** [comment] 2021-02-05 15:10
Closing, as duplicate of #2565 :)

**Closed by bromagosa** 2021-02-05 15:10 UTC
