### ISSUE TITLE
Comments on variables lost when project reloaded

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2032] opened 2018-02-25 10:56 UTC
The following comment disappears when loaded:

![image](https://user-images.githubusercontent.com/2138696/36640616-178c1386-1a55-11e8-9e48-6592b4391058.png)

**Comment by jguille2** [comment] 2018-02-25 12:04
OOpss! Yes, you're right :(

The problem is that anchor comments are `<comment>Comment...</comment>` inside the `<block>....</block>` expression... and "variable blocks" are `<block var="x"/>`  (a self-closing block)!

**Comment by jmoenig** [comment] 2019-06-03 14:10
Since @jguille2 has fixed this issue, it can now be closed. Thanks!

**Closed by jmoenig** 2019-06-03 14:10 UTC
