### ISSUE TITLE
isRetinaSupported() doesn't match checks in enableRetinaSupport()

### ISSUE THREAD

**Issue by SArpnt** [jmoenig/Snap#3396] opened 2024-09-17 01:09 UTC
the relevant code sections:
[enableRetinaSupport](https://github.com/jmoenig/Snap/blob/befa1840df87b25e0ef5b3d6446b99fbd48b3260/src/morphic.js#L1763)
```
var originalDevicePixelRatio = Math.ceil(window.devicePixelRatio);
if (backingStorePixelRatio === originalDevicePixelRatio) {return; }
```
[isRetinaSupported](https://github.com/jmoenig/Snap/blob/befa1840df87b25e0ef5b3d6446b99fbd48b3260/src/morphic.js#L1966C5-L1966C62)
```
return backingStorePixelRatio !== window.devicePixelRatio && ...
```

enableRetinaSupport checks the ceiling of the device pixel ratio, while isRetinaSupported checks it directly.
i don't fully know the implications of this, but given the context i would expect these to match, and ideally the code wouldn't be duplicated. maybe enableRetinaSupport could be rewritten to use isRetinaSupported, or both to use another shared function?

on another note if you don't mind me asking here, what exactly is backingStorePixelRatio? it isn't documented anywhere, my browser doesn't have it, and the provided link is dead.

**Comment by jmoenig** [comment] 2024-09-17 06:22
yes, this was caused by a bug in either Chrome or Firefox - I'm pretty sure it was Chrome - a few years ago that would break Canvas in case of non-integer devicePixelRatio settings. For a couple of years Google used to break Canvas *every* fall at the beginning of class, and it always looked it was Snap's problem, and then by Christmas they'd fix it again, but by then the semester was already over.

I'm not aware of any current problems, so we can probably take this out again. OTOH, it doesn't cause any problems either, so I'm reluctant to.

Closing.

**Closed by jmoenig** 2024-09-17 06:22 UTC
