### ISSUE TITLE
Enhancement: shift-right-click on command blocks...

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#2296] opened 2018-12-28 05:19 UTC
... even though mostly there isn't a result to show in the script pic.  This would be useful when the command produces an error message, which does come up in teaching materials pretty regularly.

Very low priority, but I'm hoping very easy too.

**Comment by cycomachead** [comment] 2019-01-04 01:41
Duplicate of #1777

**Closed by cycomachead** 2019-01-04 01:41 UTC
