### ISSUE TITLE
Apostrophes in input names

### ISSUE THREAD

**Issue by tjvr** [jmoenig/Snap#293] opened 2014-01-04 22:56 UTC
1. Create an input
2. Name it `oh 'gosh', I'm a chicken!`
3. The words `a chicken!` get added to the end of the block's text
4. Select OK
5. Edit the block again
6. The apostrophes have mysteriously vanished.

I'm concerned about this mainly because I'm not sure how precisely to parse/generate block selectors in Snap! XML files.

**Comment by bromagosa** [comment] 2019-08-29 18:06
Closing as duplicate of #1295. I know this one is older, but that one is more updated...

**Closed by bromagosa** 2019-08-29 18:06 UTC
Labels: bug, low priority
