### ISSUE TITLE
Microphone dropdown

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2354] opened 2019-03-13 21:47 UTC
![image](https://user-images.githubusercontent.com/6549787/54316825-00216b80-45b8-11e9-8206-369ae09bec7a.png)

Brian and I agree that these menu items should be
- volume
- midi note
- frequency
- volume samples
- frequency samples
- number of samples

Thanks! :)

**Comment by jmoenig** [comment] 2019-03-13 22:10
thanks!
I did think a lot about how to name these, but will reconsider...

**Comment by jmoenig** [comment] 2019-03-17 15:42
okay, how about

* leaving out "midi", and just saying "note"
* "signal samples" instead of "volume samples"

and otherwise switching to your suggested wordings ("frequency" instead of "pitch", "frequency samples" instead of "frequencies", and "number of samples" instead of "bins"?

Would that be okay for you?

**Comment by MichaelHuke** [comment] 2019-03-17 17:41
Hello Jens,
I saw the block last Friday in Walldorf and I would propose "frequency spectrum" instead of "frequency samples". Looking at it as a physics teacher, this is much clearer. 
And I would prefer "volume samples" instead of "signal samples".

Cu Michael

**Comment by jmoenig** [comment] 2019-03-17 18:01
Hi, Michael!
I like "frequency spectrum". If we change to that we could just say "samples" to what is now called "signals", without risking any ambiguity, don't you think? I'm reluctant to use "volume", because it's really about amplitudes from which the volume - among other things - can be derived in non-trivial ways.
Also, if we switch to "frequency spectrum" what would be a good name for what is currently called "bins"?  This is the length of the list answered for either the samples or the spectrum, governed by the non-persistent "microphone resolution" setting (usually at 512 to make it more "lively")? Should we just say "number of bins"? Or how about "length of signals"?
Thanks

**Comment by brianharvey** [comment] 2019-03-17 20:20
"Frequency spectrum" and "samples" are great.  I don't understand "note" and "frequency": are they the lowest frequency in the Fourier transform, the highest-amplitude frequency, or something else?  (I hafta document this...)

But mainly I'm having trouble thinking about "bins."  I know it means the size of the list, but I don't understand how the spaces are used.  For samples, does "bins" change the sampling frequency, or does it change the total time sampled?  And for frequencies, does it change the total frequency range shown, or does it change the resolution within a fixed frequency range?  The best name will depend on these answers, I think.

**Comment by jguille2** [comment] 2019-03-17 20:40
Hi!
Only a "note" about **_bins_**

I think we must put the same name into the Settings menu and in this reporter. So if in the menu you have "**Microphone resolution**", we can use also "resolution" in that dropdown, I think.

If you think resolution is a bad name, we need to change also the menu.

What it is clear, is that "bins" is cryptic. In my current and free translation to Catalan, I translated "bins" with "resolution" to offer an understandable concept.
Joan

**Comment by jmoenig** [comment] 2019-03-17 22:34
good idea, we can say "resolution" instead of bins, if y'all agree.

Brian, the "frequency" is my shot at determining the dominant frequency. I'm currently not using the fft bins for this, but a somewhat naive (albeit surprisingly effective) autocorrelation algorithm that basically looks at the zero-passes for decent correlations. But I don't think you have to document the method, the outcome is the frequency that corresponds to the signal. The note is just the equivalent value that you can write into a ```play note``` block to get the same tone.

I'm conflating two values for "resolution", the signal buffer length and the frequency bins, the idea is to only have a single setting. Increasing the buffer size improves the pitch detection in general, but especially for frequencies below 180 hz. Increasing the fft size - and thus the frequency bins - lets you see more overtones in the spectrum. but takes longer. Performance varies dramatically on different machines and browsers (don't get me started on Safari, gosh...), so I chose a relatively small default setting to make it interesting on a wide variety of setups.

So, can we agree on:

volume
note
frequency
samples
spectrum
resolution

?
Thanks!

**Comment by brianharvey** [comment] 2019-03-17 23:55
"Resolution" is right for the number of bins only if the total duration of the sampled sound is constant (e.g., one second).  If increasing the number of bins instead increases the amount of time sampled, at the same sample rate, then no.

I think you think you've answered this, but if so, it's based on some (probably "obvious") unstated assumptions.  Could you please say precisely what it is you are holding constant?  (E.g. "the block always samples two seconds of sound" vs. "the sampling frequency is always 44KHz.")  Similarly, in the frequency domain, what are you holding constant, and at what value?  (E.g., "the highest frequency reported is always 22KHz" vs. "the width of one frequency band is always 50 Hz.")

Thanks!

**Comment by jguille2** [comment] 2019-03-18 09:16
Uf!

Yes, but the problem is not about units. Units are not an easy explainable concept here, because the fftSize represents the window size in samples that is used when performing a Fast Fourier Transform (FFT) to get frequency domain data.

Then, what we have is that a higher value will result in more details in the frequency domain but fewer details in the time domain.

So, the "right" name could be "Frequency resolution", because if we increase "bins" we get a more detailed frequency data but not exactly a "more detailed sound".

I don't know if this "frequency resolution" is a name too long or not...

**Comment by jmoenig** [comment] 2019-06-03 05:37
this is has been resolved, I think. Closing...

**Closed by jmoenig** 2019-06-03 05:37 UTC
