### ISSUE TITLE
How to use the ñ key?

### ISSUE THREAD

**Issue by introlinux** [jmoenig/Snap#1403] opened 2016-09-04 07:53 UTC
Hi, I'd like to use the ñ key (in a spanish keyboard), but in the hat "when %key key pressed" is not this key. Then I tryed the "any key option" in this way:
![](https://s11.postimg.org/6styp3wv7/key.png)

But it didn't work.
It is very strange, because the "any key" can detect perfectly when I press the ñ key here:
![](https://s21.postimg.org/x2cttrfmv/key2.png)

What is the right way to do this?

**Comment by dekrain** [comment] 2016-09-04 08:28
`key pressed`, like `when key pressed` block don' t implement your key

**Comment by liam4** [comment] 2016-09-04 10:58
At the moment there is no right way, aside from your workaround, I believe, but making the key-pressed input like this would probably be nice:

![editable dropdown](https://cloud.githubusercontent.com/assets/9948030/18230544/2c23bfa8-7275-11e6-9877-6f0a2df0fd3d.png)

The dropdown would contain all the usual letters, and you'd be able to type your own letter in the dropdown input as well.

Only issue of course is putting in something like "abc".

(I suppose the usual thing is "but all curriculum writers would have to change their screenshots to match this!"... though this is a pretty small detail.)

**Comment by brianharvey** [comment] 2016-09-04 14:24
@liam4 We're not going to say that.  The key-pressed block is not something central like list display, and the difference is not hard to understand.

@introlinux Yes, we should support this; it's part of internationalization.  We'll get to it.

**Comment by Jonathan50** [comment] 2016-09-05 00:10
> Only issue of course is putting in something like "abc".

Could you make a "letter" input type?

Also then you wouldn't have to scroll lots to find the letter anymore.

**Comment by cycomachead** [comment] 2016-09-05 04:15
I think what's possibly going on here, though I'd have to check, is that `ñ` is actually _two_ keypresses: `˜` and `n`, which together create the proper key. Tied with all the stuff going on with #4 (and the related issues), we might want get all that working first, then first out if we can have `key pressed` somehow handle compound inputs.

**Comment by bromagosa** [comment] 2016-09-05 08:03
Nope, the ñ is one single keypress and a distinct letter, just as ç is. Ther is a specific key for each of these :)

**Comment by bromagosa** [comment] 2019-07-24 07:40
(Closing as duplicate of #683)

**Closed by bromagosa** 2019-07-24 07:40 UTC
Labels: enhancement, good student project, i18n
