### ISSUE TITLE
(unicode (unicode of []) as letter) runs forever

### ISSUE THREAD

**Issue by waluigispear** [jmoenig/Snap#2368] opened 2019-04-07 05:05 UTC
![untitled script pic](https://user-images.githubusercontent.com/48372183/55678957-496b8f00-58c8-11e9-94e5-30bf91d97225.png)
This (the string input is blank) will run forever (presumably - I let it run for 3 minutes and it didn't finish). This occurs both in the stable and the beta.

Using Chrome 73.0.3683.86 on Windows 7

**Comment by brianharvey** [comment] 2019-04-07 05:26
Fixed in PR #2369.

It doesn't matter what the outer block is; the problem is that the inner block returns undefined, which doesn't work as an input value.

**Closed** 2019-04-07 06:50 UTC
