### ISSUE TITLE
saving project to file doesn't save drop down list correctly

### ISSUE THREAD

**Issue by sdmeijer** [jmoenig/Snap#788] opened 2015-04-28 18:44 UTC
When saving a project with a custom block with a drop down list, the options aren't saved correctly. And therefore the dropdown list in that block is incomplete when importing this project.

In the project-xml-file the options are saved as:
option 1=somethingoption 2=somethingoption 3=something

When exporting block the options are saved as
option 1=something option 2=something option 3=something

**Comment by jmoenig** [comment] 2015-04-29 00:55
Hmmm.... can you share a project, I cannot reproduce this. Are you using IE? Thanks!

**Comment by sdmeijer** [comment] 2015-04-29 13:47
Export of block: http://pastebin.com/Kt5u6785
This works fine.

Export of project (with only the above block): http://pastebin.com/xMuE3iMC
After importing this project, the drow down list only holds 1 option.

**Comment by jmoenig** [comment] 2015-04-29 15:02
Hmm... When I import your block into my Chrome, export the project and then re-import the project into a new project, the block doen't change, I'm always getting your zillions of choices...

**Comment by sdmeijer** [comment] 2015-04-29 15:20
I've used 'Save to disk'.

**Comment by jmoenig** [comment] 2015-04-29 19:38
Cool project!
Yes, "save to disk" sometimes messes up exported projects. This seems to happen more often in Chrome than in FF, but in this particular case FF is also acting bad.
I'm considering "hiding" the 'save to disk' item again, as it's apparently not (yet) well supported even in those browsers claiming to support it... :-(

**Comment by jmoenig** [comment] 2019-06-03 16:05
This should now be fixed. Closing...

**Closed by jmoenig** 2019-06-03 16:05 UTC
Labels: important
