### ISSUE TITLE
Adding title text removes variadic inputs?

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2908] opened 2021-11-09 23:38 UTC
Hi Jens,
I have this block with inputs:
![untitled script pic (68)](https://user-images.githubusercontent.com/6549787/141022724-2bdf6fa4-6960-40e7-a0df-f6536d2761b1.png)
And I change the title text from
![untitled script pic (69)](https://user-images.githubusercontent.com/6549787/141022747-6a06cf9e-fc09-4dfa-82d1-a8fb5849d0de.png)
to 
![untitled script pic (70)](https://user-images.githubusercontent.com/6549787/141022787-99d73b5e-9035-43af-8658-d7736ed04dcf.png)
and it deletes my inputs in the block in the scripting area
![untitled script pic (71)](https://user-images.githubusercontent.com/6549787/141022801-9dff6d4b-2cd1-4c4a-bc37-c9d33a8c69ea.png)
That's a bug, right?

**Comment by WarpedWartWars** [comment] 2021-11-10 02:06
It's a known bug. (There are various other topics about this.)

**Comment by jmoenig** [comment] 2021-11-17 17:12
duplicate of #2760 #2445 #1809.
Just a quick note why this is tricky, even though it's been reported often: a "variadic" input is handled as a *single* element (one that evaluates to a list) internally. When we change the structure of a block we try to restore the contents of its inputs, and this is surprisingly hard to get right for variadic ones, especially since you can also drop a reporter *onto* the *whole* variadic input (not *inside* one of its slots).
I'm not saying it's impossible (and I'm not asking for advice) but that's the reason why you have to know it's way harder to do than one might expect.

**Closed** 2022-02-09 16:11 UTC
