### ISSUE TITLE
Adding labels to sprites

### ISSUE THREAD

**Issue by TheInfinityUser** [jmoenig/Snap#2625] opened 2020-07-05 11:32 UTC
Please add an option to be able to label sprites. It helps a lot.

**Comment by jmoenig** [comment] 2020-07-05 12:14
did you know that you can double-click on a sprite on the stage in edit mode to see which one it is in the corral? likewise you can double-click on a sprite-icon in the corral to highlight it on the stage? Does that address your issue?

**Comment by TheInfinityUser** [comment] 2020-07-05 12:17
I don't think so. I want a label that you can enable using a script and you can use scripts to change the content, position, colour, and so on of the label and the text feature isn't applicable for this purpose.

**Comment by jmoenig** [comment] 2020-07-05 12:37
Okay, I'm afraid I don't understand what it is you're suggesting/requesting. programmable text boxes?

**Comment by TheInfinityUser** [comment] 2020-07-05 14:05
Exactly

**Comment by brianharvey** [comment] 2020-07-06 01:00
This has been on my todo list since forever.  Maybe we should move it up.

**Comment by TheInfinityUser** [comment] 2020-07-06 02:06
You can add it as an extra library.

**Comment by jmoenig** [comment] 2020-07-23 09:55
duplicate of #2314

**Closed by jmoenig** 2020-07-23 09:55 UTC
