### ISSUE TITLE
student managed to save project with modified primitives

### ISSUE THREAD

**Issue by brianharvey** [jmoenig/Snap#3393] opened 2024-09-06 19:04 UTC
I thought that modifications to primitive blocks weren't saved with the project, but here is a copy I made in my directory of a misbehaving student project:

https://snap.berkeley.edu/snap/snap.html#present:Username=bh&ProjectName=art%20with%20polygons

(copied in case the student modifies their own version).  It looks to me as if the student at some previous time loaded the project into TurtleStitch, saved it there, then loaded into Snap_!_ 10.0.  The result is that some of the Motion primitives have apparently been changed into TurtleStitch versions.  Specifically, GO TO [RANDOM POSITION] errors because it refers to a nonexistent variable _EMBROIDER.

I agree that the source of this difficulty is a prior weird wrong choice by the student.  Still, the result is that the teacher couldn't figure out what was wrong, because the modifications to primitive blocks weren't apparent in the palette.

Even if we consider this a bug in TurtleStitch rather than a bug in Snap_!_, I think this will happen again, and we should code defensively against it.

**Comment by jmoenig** [comment] 2024-09-06 20:42
No, customized primitives are saved in the project, otherwise things like the Embroidery library would never work. This project is weird in many ways. Once you've started an Embroidery project you cannot easily decide to "unload" the Embroidery library again. It looks like somebody started from an Embroidery project and then tried to manually get rid of the blocks, which - of course - doesn't work, because the primitives have been customized and remain that way.

There is an emergency gimmick to reset the customized palette blocks back to their primitive "factory" state: Shift-click on the gear  button and select "Primitives Palette" in the settings menu.

<img width="616" alt="revert customized primitives" src="https://github.com/user-attachments/assets/3c17d739-f7fd-4172-9d33-a585fd7028b7">

This fixes it.

I'm almost 100% sure that this is not a student mistake but caused by some hackish starter project given to them by a hackish curriculum developer :)

**Comment by brianharvey** [comment] 2024-09-06 20:59
Nope, I promise, this isn't anything the student found in BJC starter projects.

I suppose it's _possible_ that someone at EDC made a _script pic_ after having imported libraries for some other purpose.  BJC predates smart script pics, but some pictures were redone so as to be translatable into Spanish.

Why do you think it couldn't just be that the student randomly imported Embroidery out of curiosity?

**Comment by brianharvey** [comment] 2024-09-06 21:01
PS  And I still think it needs to be visible somewhere in the GUI that there are modified primitives in a project.  Teachers will never think to check for that otherwise.

**Comment by ego-lay-atman-bay** [comment] 2024-09-06 21:04
What if there's a small button that appears next to modified primitives that when clicked, will reset the primitive.

**Comment by jmoenig** [comment] 2024-09-06 21:37
perhaps an option in the block editor to reset the primitive would be a good idea, yeah.

**Comment by brianharvey** [comment] 2024-09-07 01:09
@ego-lay-atman-bay 
I've always been adamantly against doing anything that would distinguish primitives from custom blocks in the palette; once you've defined a procedure, it should be just as well respected as a primitive.  But maybe I'd make an exception for custom blocks that are shadowing primitives... but then when you use the Embroidery library it rubs your nose in the fact that GO TO (or for that matter MOVE) doesn't mean what you think it does.  So I think I still want one global "there are modified primitives" indicator, maybe up next to the pencil for an unsaved project.

**Comment by cycomachead** [comment] 2024-09-07 01:58
I think there should be something more visible to teachers but I don’t know if it needs to be every block in the palette with an icon. Maybe we should have somewhere that shows all the overridden primitives? And that button only appears if there are any present. -- Michael BallFrom my iPhonehttps://mball.coLecturer UC Berkeley EECS | Travel Advisor Fora On Sep 6, 2024, at 6:10 PM, Brian Harvey ***@***.***> wrote:﻿
@ego-lay-atman-bay
I've always been adamantly against doing anything that would distinguish primitives from custom blocks in the palette; once you've defined a procedure, it should be just as well respected as a primitive.  But maybe I'd make an exception for custom blocks that are shadowing primitives... but then when you use the Embroidery library it rubs your nose in the fact that GO TO (or for that matter MOVE) doesn't mean what you think it does.  So I think I still want one global "there are modified primitives" indicator, maybe up next to the pencil for an unsaved project.

**Comment by jmoenig** [comment] 2024-09-07 07:11
> Why do you think it couldn't just be that the student randomly imported Embroidery out of curiosity?

because I'm having troubles reproducing this behavior in a fresh project. The variable named "_embroider" does *not* get removed when I unload the unused blocks of the Embroidery library. Something fishy has gone on here.

**Comment by jmoenig** [comment] 2024-09-07 07:17
Turns out I forgot that there already *is* an indicator for customized primitives: When you select "export blocks" you see a list all custom blocks that *includes* the customized primitives. Likewise in the palette block's context menu there will be an option to  "delete block definition", which resets it to the primitive (also using metaprogramming, if you wish):

<img width="235" alt="reset customized primitive" src="https://github.com/user-attachments/assets/762823ef-c9d7-4d51-8a63-ab601de838b8">

You can find this out and perform this on a per-block basis without having to resort to the somewhat hidden shift-click menu gimmick.

**Comment by DarDoro** [comment] 2024-09-10 07:25
Modified primitives should have a "visual indicator", say a small dot in the corner. Otherwise, it will be a nightmare to support users who have a modified primitive in the project and don't know/forgot that.

**Comment by jmoenig** [comment] 2024-09-10 07:34
... and that's why I've resisted for ages to add this functionality to Snap!, but all the time those old LOGO folks have been twisting my arms to the point of breaking them, claiming that I'm mistrusting kids and imposing my design on them. Naw, with v10 basically *every* block in the system can now be a custom blocks, you cannot be sure. But you can edit every block to find out what it does an if it's a primitive or not. To be fair, even before v10 quite a lot of projects had custom blocks in them that looked *exactly* like primitives but did something else, and those occasionally tricked / pranked teachers into puzzlement. But it's also true that those occurrences were very rare and that the benefits of being able to customize primitives probably vastly outweigh those downsides.

**Comment by brianharvey** [comment] 2024-09-10 16:29
To be fair, in text languages there's no display of primitives in the first place, and people cope somehow.  I'm not suggesting that text languages should set the bar for how helpful our UI should be; I'm just suggesting that there's no need to panic.

I think the current situation with modified primitives is _less_ confusing than having two identical-looking blocks, one primitive and one custom, in the palette and then having no way to tell which one is being used in any particular script (except by right-clicking).  Now that we have modifiable primitives, we shouldn't let people make identical-looking custom blocks, except we have to support old projects, sigh.

It might be useful if we actually knew whether in fact that situation is in "quite a lot of projects" or "very rare."  :)  That would give us a way to predict how people will use the ability to modify primitives.

I think deliberate pranks are just a fact of life given how computers are and how kids are.  When I was running a high school computer center, I worked hard to establish community standards that (1) you're only allowed to play tricks on people more experienced than yourself, and (2) you have to make sure that the victim doesn't end up deleting his own files in confusion.  I don't recall any truly hostile messing up someone else's environment; there were a few hostile acts, but they were unsubtle, just deleting the other person's files.  And not even very many of those.

I'd be more worried about inadvertent corruption of a project.  Not _very_ worried, because it's not easy to do by accident.  It's much more likely for someone to create a custom block that happens to look like a primitive than for them to _edit_ the primitive and not notice that there's already code there.

On the other hand, I think it's pedagogically useful to be able to build projects with modified primitives and not have the modification jump out at you.  One application, for example, would be to instrument some primitives to log when they're used.  Another, which I bring up timidly because I know you, Jens, hate it, is the bignums library.

I'm wondering if we shouldn't compromise on having a debug mode in which we mark modified primitives and maybe add other aids to debugging such as the pause-on-error feature I've always wanted.

Gotta go to a meeting so I'll stop here...

**Comment by jmoenig** [comment] 2024-09-11 07:14
Yeah, so now we've seen the second case of this in the forums. I'm thinking that it might be useful to add a menu item to the project ("file") menu to let users "Reset primitives". That item would only be shown if the current project/scene has customized primitives, same as the "Export blocks" and "Unused blocks" options. I'd add it underneath "Unused blocks". This would add both an easy way to find out whether a project customizes primitives and a one-click option to reset them. Of course, if somebody uses e.g. the Embroidery library and "accidentally" resets the primitives that would break their project. However, as with any library, re-importing the Embroidery library would again "fix" that. What do y'all think about this?

**Comment by ego-lay-atman-bay** [comment] 2024-09-11 07:22
I don't know if you were implying this, but I feel like it should have a dialog that allows you to see which primitives were customized, and be able to select specific primitives you want to reset.

**Comment by ego-lay-atman-bay** [comment] 2024-09-11 07:36
I personally feel like it's more obvious if they're also separated into their own dialog. Plus, it'll be an easy place to select specific customized primitives and delete them, since they currently don't show up in the unused blocks dialog.

**Comment by jmoenig** [comment] 2024-09-11 07:47
Sure, but I really don't want this to be such an indirectly "big thing" in any way. Making a special dialog for just this "reset" feature imo totally overblows it out of proportion, besides making it a highly indirect way to interact with blocks. Instead, having projects / scenes with customized primitives should probably become something very common in the future. So I'd like people to get used to just directly right-/option-click and editing *any* block in the palette, and to also just delete unwanted customizations *directly*.

**Comment by brianharvey** [comment] 2024-09-11 07:49
That's fine with me.  (The simple reset option.)

**Comment by ego-lay-atman-bay** [comment] 2024-09-11 07:51
Yeah, I guess so. I mean, it is your decision after all, not mine.

**Comment by jmoenig** [comment] 2024-09-11 07:55
> That's fine with me. (The simple reset option.)

Thanks, Brian. I'm considering adding this for a quick patch later this week, so it gets out into production before the "hidden setting" hack becomes known as the "right way" to address this :)

**Comment by SArpnt** [comment] 2024-09-17 00:58
> To be fair, in text languages there's no display of primitives in the first place, and people cope somehow. I'm not suggesting that text languages should set the bar for how helpful our UI should be; I'm just suggesting that there's no need to panic.

most languages require importing what's used into every file, and most projects use plenty of files with easy to understand imports. in every text language where you can override any kind of builtin, nearly all developers are against doing so even for polyfills. in any language where things from multiple files can go in the same scope (for example, global scope like js, or no namespaces like c) most developers are against putting things in a shared scope, and if the language forces it (like c again), then most developers use long names with clear prefixes to reduce the chance that any two things will conflict best they can.

unfortunately, in snap, all blocks are accessible everywhere all the time. there is no way to see what blocks are from what libraries. this causes a lot more problems than confusion about which blocks are primitive or not, it makes it nearly impossible to update libraries, to remove libraries, to share libraries, to know where blocks are used so bugs can be fixed, etc.

and yes, i'm aware that the code for snap itself puts everything in the global scope. that's not a good thing. exactly like in snap, it makes it nearly impossible to make changes without breaking *something somewhere* because there's very often some weird use case off in some unusual bit of code or even something completely accidental. many functions in snap have to check that all their inputs are valid or do slow fixing of things afterwards even when not needed because it's impossible to anticipate when they might be used in a situation where they weren't meant to be used.

i think the ideal way editing primitives and library blocks would work is that you can *view* the contents, but not edit them. all you can do is drag blocks out of the window. libraries should always have their own categories separate from the primitive categories, and both the primitive and library categories should also be impossible to edit. any custom blocks should go in new categories.
unfortunately i don't think this is compatible with existing projects. i guess the best option would be to place the custom blocks at the bottom of the palettes and make the primitive/library blocks read only. existing primitive/library edits would become new blocks that happen to have the same name (also confusing, but snap can already *sometimes* do this, so that's a separate issue)

**Comment by ego-lay-atman-bay** [comment] 2024-09-17 18:37
> in every text language where you can override any kind of builtin, nearly all developers are against doing so even for polyfills.

I think it's worth mentioning that I know of an example of a library overriding a builtin function. That example is the python `rich` library. It's a library that makes it easier to print beautiful (colored) stuff to the console (including printing better error messages). The library lets you choose to override the builtin `print()` function to be able to use the beautiful printing instead of python's bland printing.

I'm really pointing this out, because there are uses cases for overriding primitives in text languages, so I don't see why snap shouldn't give you the ability to do so too.

**Comment by SArpnt** [comment] 2024-09-18 15:41
> The library lets you choose to override the builtin `print()` function to be able to use the beautiful printing instead of python's bland printing.

but that doesn't do the same thing. that *optionally* lets you use the rich "print" function in a specific location, which happens to have the same name. because of how the names work, in the code it's effectively replaced. the original print function never changes, and can still be used if you make another name for it beforehand. i'm not familiar with python but considering how imports work in most languages i'm guessing you also have to do it in every file.

in snap, if you override a primitive, you no longer have it *anywhere*. not even to use inside your new say block! in many cases when overriding an existing function in a language, you still want to use the original.

this is much closer to your python example, and doesn't modify the primitive: https://snap.berkeley.edu/project?username=sarpnt&projectname=overriding%20primitives%20without%20modifying%20them

**Comment by jmoenig** [comment] 2024-09-18 16:06
> in snap, if you override a primitive, you no longer have it _anywhere_. not even to use inside your new say block!

Let's not just write wild claims. If you customize a block in the palette you can still use the original primitive, even *inside* your new block: You can make another custom block that uses the primitive block (check the Embroidery library, it does just that). Also, it's really easy to reset the customized primitive: Just delete it.

Okay I've adressed this issue in the dev version, there will be a menu entry to reset all prims, as we decided. Closing this issue now.

**Closed by jmoenig** 2024-09-18 16:06 UTC
