### ISSUE TITLE
Inhereted sprite icons dragging

### ISSUE THREAD

**Issue by haritop** [jmoenig/Snap#1094] opened 2016-01-02 19:09 UTC
Have a look at this
![snapbug](https://cloud.githubusercontent.com/assets/8059587/12075784/ee754a4c-b194-11e5-84e7-5bb3b3d68ee6.gif)

Update:
Tested in Chrome and Opera.
In Firefox it behaves normally most of the times(it stuck only once in the upper left corner of the stage)

**Comment by jmoenig** [comment] 2016-01-02 23:10
I cannot reproduce this.

**Comment by haritop** [comment] 2016-01-03 01:41
I've tested this on chrome (both 64 and 32 bits), on different windows 7 64-bit machines.
It did not happen on chrome for Android.
The strange thing is that when you set parent to none, the icon behaves normally again.
It happens only on sprites with their parent attribute set to another sprite.
The Chrome version is 47.0.2526.106

**Comment by jmoenig** [comment] 2016-01-03 11:03
Thanks! Yes, I can now reproduce this mysterious bug on Windows. Strange this is this happens *only* on Windows and it doesn't even trigger a JS error in the console.

Did I mention that I hate browsers?
... and also operating systems. (there shouldn't be one: http://web.archive.org/web/20070213165045/users.ipa.net/~dwighth/smalltalk/byte_aug81/design_principles_behind_smalltalk.html)

**Comment by jmoenig** [comment] 2019-06-03 17:50
Hmmm... is this still happening?

**Comment by haritop** [comment] 2019-06-04 09:50
No it does not. Not in version 4.2.2.9 nor in version 5. I think this has stopped happening a long time ago(probably cured by a browser update).

**Comment by bromagosa** [comment] 2019-06-04 10:45
Closing, then :)

**Closed by bromagosa** 2019-06-04 10:45 UTC
Labels: browser-specific, bug
