### ISSUE TITLE
Comment stuck and "shadowing"

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1804] opened 2017-07-13 15:43 UTC
I tried to drop a comment on another sprite (like you can do with a script), and it got stuck. I can't move it anymore, and when I try, it just makes the shadow longer and longer.

![broken-shadow](https://user-images.githubusercontent.com/6549787/28174760-6b761476-67c0-11e7-85d4-23daf29542bd.gif)

**Comment by jmoenig** [comment] 2017-07-13 15:50
Hmm... I can't reproduce this, it works for me.

**Comment by maryfries** [comment] 2017-07-13 15:52
I closed and reopened the project, and the rouge comment was gone. I couldn't reproduce it, but I was not able to get a comment to copy over to another sprite either. Is that possible for comments the way it is for scripts?

**Comment by jmoenig** [comment] 2017-07-13 15:55
comments can't be copied by dragging them onto other sprites. But if a comment is attached to a block or script, dragging *that* over to another sprite also copies the atteched comment(s).

**Comment by brianharvey** [comment] 2017-07-28 21:31
Workaround:  Put the comment in multiline mode, copy the text, then make a new comment in the other sprite and paste the text.

**Comment by jmoenig** [comment] 2019-06-03 17:45
could be related to #670

**Comment by maryfries** [comment] 2019-06-03 18:32
I can still reproduce this. Specifically, it happens if you duplicate a comment and then drop the duplicate comment on the other sprite _before_ dropping it at least once in the scripting area.

![comment-bug](https://user-images.githubusercontent.com/6549787/58825376-57aa0300-860c-11e9-9371-a3ce27cda670.gif)

**Comment by jmoenig** [comment] 2019-06-03 19:19
Yes, it's totally reproducible and clear. I self-assigned this issue so I remember to fix it for 5.0 ;-)
Thanks!

**Comment by jmoenig** [comment] 2019-06-03 21:06
I've just fixed this for #670. Closing. @maryfries can you confirm this is fixed (if it's not, please reopen, I'm going to bed now ^^). Thanks!

**Closed by jmoenig** 2019-06-03 21:06 UTC
Labels: can't reproduce

**Comment by maryfries** [comment] 2019-06-03 21:14
Looks good to me!! Thanks!
