### ISSUE TITLE
Chrome randomly preventing using the write block

### ISSUE THREAD

**Issue by R4356th** [jmoenig/Snap#2599] opened 2020-06-02 10:17 UTC
On Chrome, I once failed to use the write block. Trying to operate a command with it returned no errors but did not do anything (only the write block, the others were just fine. I wonder if this is a Morphic or a Chrome bug. It left me [confused](https://forum.snap.berkeley.edu/t/why-is-it-not-possible-to-conduct-mathematical-operations-and-write-the-value-on-the-screen-with-the-write-block/2065/) because I did not have to do anything to get rid of it like clearing my browser caches. It got fixed by itself!
My Chrome version is 83.0.4103.61 (Official Build) (64-bit).

**Comment by jmoenig** [comment] 2020-06-09 10:22
can't reproduce, closing

**Closed by jmoenig** 2020-06-09 10:22 UTC

**Comment by R4356th** [comment] 2020-06-11 07:36
Well, @jmoenig, I did say 'randomly'!
