### ISSUE TITLE
Can't see last library

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2468] opened 2019-07-29 21:08 UTC
We want to use the last library in Snap, but it's not visible due to the scroll bar. 

![image](https://user-images.githubusercontent.com/6549787/62082768-68997e00-b223-11e9-9b5f-a72ce2fb2d0d.png)

Can this be fixed quickly, so we can use it ASAP?

**Comment by jmoenig** [comment] 2019-07-29 21:17
sorry, this is not a quick and easy fix, if at all. But you can simply resize the dialog slightly, just make it a little bit taller, then you can see and select the string library.

**Comment by maryfries** [comment] 2019-07-29 21:18
So, we need to write the workaround into BJC?

**Comment by jmoenig** [comment] 2019-07-29 21:21
Huh? We can make the library dialog slightly taller, that'll solve it.
But, another thing. Are you really thinking about using the string library in its current form for BJC? I'm totally not convinced about it, it's way too stateful, and the whole business of upper- and lowercasing seems terribly experimental, to put it very mildly. But that's a different issue. I was under the impression that somebody wants to try some things with that library, but - good grief - not use it for a real curriculum....

**Comment by maryfries** [comment] 2019-07-29 21:26
Yes, to cover this standard: "AAP-2.D.2: A substring is part of an existing string."

**Comment by jmoenig** [comment] 2019-07-29 21:27
![string_library](https://user-images.githubusercontent.com/2596285/62083938-58e85c80-b258-11e9-960d-a10028187285.gif)

**Comment by brianharvey** [comment] 2019-07-30 07:15
The original purpose was scraping web pages, but what's experimental about it?  It just calls Javascript functions.

**Comment by cycomachead** [comment] 2019-08-05 07:13
Regardless of BJC, this is one of those thing about Snap<em>!</em> that's confusing and frustrating. There will always be something at the bottom of the list you need. Like maybe a project.

**Comment by cycomachead** [comment] 2019-08-05 07:57
This is a bit annoying to fix, but it shouldn't be that hard. Maybe I'll figure it out before bed time. 😀

**Comment by cycomachead** [comment] 2019-08-05 08:22
OK, got a fix. Yeah, a bit confusing, but I'm pretty sure this Just Works now. 🙂

**Comment by cycomachead** [comment] 2019-08-05 08:37
See #2470 

duplicate of #638

**Comment by cycomachead** [comment] 2019-08-05 08:37
duplicate of #638

**Closed by cycomachead** 2019-08-05 08:37 UTC
Labels: morphic
