### ISSUE TITLE
says logged out but also logged in

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#2204] opened 2018-09-07 17:20 UTC
Clicking the cloud menu gives me the logout option as if I'm logged in, but saving or opening from the file menu says I'm not logged in. I logged in about an hour ago.

This has been happening lately—especially if I don't choose the "stay signed in" box.

**Comment by cycomachead** [comment] 2018-09-11 04:12
I think you basically need to choose the "remember me" checkbox. The menu doesn't update always, because it doesn't actually know whether or not you're logged in. 

It seems that the way the new cloud handles logins that if you don't check the box, the session is very  show.

**Comment by cycomachead** [comment] 2018-09-11 04:43
OK, I reviewed some stuff on the cloud system and I think we can fix the issue with needing the check the remember me box and then things should be more stable.

**Comment by maryfries** [comment] 2019-04-03 18:25
This happened again today...

![image](https://user-images.githubusercontent.com/6549787/55503281-5d8b6400-561c-11e9-885b-bb0292ec7a5c.png)

**Comment by maryfries** [comment] 2019-09-25 20:35
It happened again today.

**Comment by maryfries** [comment] 2019-12-17 18:34
Is this related? https://piazza.com/class/h8yx482idav52y?cid=3112

**Comment by bromagosa** [comment] 2019-12-17 20:38
I believe these are different issues. Are these students by any chance using Chrome v77? They say they're using Chromebooks, so that may be the issue.

**Comment by maryfries** [comment] 2019-12-17 20:43
I don't know, but I added the question to the page.

**Comment by cycomachead** [comment] 2020-07-22 17:11
duplicate of #2658

**Comment by cycomachead** [comment] 2020-07-22 17:11
I am going to leave the more recent issue open if these turn out to be related.

**Closed by cycomachead** 2020-07-22 17:11 UTC
Labels: cloud
