### ISSUE TITLE
pasted-in text overruns size of text box

### ISSUE THREAD

**Issue by maryfries** [jmoenig/Snap#1873] opened 2017-09-29 21:21 UTC
![image](https://user-images.githubusercontent.com/6549787/31036526-9cfcd126-a53a-11e7-84c3-62a4ef448fe6.png)

**Comment by maryfries** [comment] 2017-10-02 15:38
I'm not sure what version I was in last week (probably dev), but today, I'm definitely in dev, and two other weird things happened. Sometimes if I move a situation like this around it will go back to normal (the text tucks inside the block as it should), but today...
1) **The block disappeared** when I tried to move it. Everything else acted normal; I could see the target input field (with the white outline) as I moved from hovering over one block to another, but I couldn't see the block I was holding until I dropped it, and...
2) When I dropped it, it landed ok, but the text did not tuck inside the block as it should have been in the first place AND **the stage went white**. 

This reminds me of https://piazza.com/class/j183gzjdzdv2gh?cid=49 (where I don't think the stage is narrow, BTW; I think the screenshot is just cropped). Not sure if this is related though, as my blocks still show...

![image](https://user-images.githubusercontent.com/6549787/31085741-fe0ce9ce-a765-11e7-9553-4d08060c6697.png)

**Comment by maryfries** [comment] 2017-10-02 15:57
Several other potentially helpful debugging points:
1) This is a very long block of input text that is mostly 1s and 0s but starts with "TEXT".
2) The staging area is now very wide and expanded over to the left, reminding me of #1722 
3) The far right of the block looks like this (empty, I expect, the same amount of space that things are pushed over on the left):

![image](https://user-images.githubusercontent.com/6549787/31085985-97d96ff0-a766-11e7-96de-ac1c32299811.png)

**Comment by maryfries** [comment] 2017-10-02 16:03
Saving and re-opening made the text fall back inside the input area of the block, but the scripting area is still white and there is still extra space on the left. 

http://snap.berkeley.edu/snapsource/dev/snap.html#present:Username=mfries&ProjectName=U6L1-TranslatingBinary(org)%20broken

And re-re-opening gave me this...

![image](https://user-images.githubusercontent.com/6549787/31087070-b4a85026-a769-11e7-9ec4-aab84f09aa83.png)

**Comment by maryfries** [comment] 2017-10-02 18:43
A few extra notes because I keep running into this even in a different file (in which I imported some of the same blocks:
1) I'm only seeing it with pasted-in text.
2) Selecting all of the inputted text sometimes will fix the problem.
3) Sometimes this happens instead of what I described above:

![image](https://user-images.githubusercontent.com/6549787/31093496-e53189cc-a77f-11e7-92a8-86546281217b.png)

**Comment by maryfries** [comment] 2017-10-03 18:06
If I use a shorter (but still long) input string length (in a copy of the file where this error has not occurred yet), sometimes things get very slow.

**Comment by maryfries** [comment] 2017-10-04 17:42
Is there any hope for fixing this? It's stalling my work on U6. Thanks!

**Comment by jmoenig** [comment] 2017-10-04 19:15
Well...
Do you really want my expert opinion on what might be the problem with this project?

**Comment by cycomachead** [comment] 2017-10-04 22:06
Duplicate of #20

**Comment by cycomachead** [comment] 2017-10-04 22:06
Duplicate of #1085

**Comment by brianharvey** [comment] 2017-10-05 03:00
@jmoenig Dunno about Mary, but I'd like it -- but maybe we can do this by email rather than github.

**Comment by cycomachead** [comment] 2017-10-05 03:22
Well, I'm curious. :P

**Comment by jmoenig** [comment] 2017-10-05 06:20
Your project contains a block that is 33 thousand pixels wide. Here's a picture of your scripts:

![u6l1-translatingbinary org broken script pic 1](https://user-images.githubusercontent.com/2596285/31212786-e3334b2c-a9a2-11e7-80fc-818f7cd52974.png)

Notice how it's super small because this forum software adjusts the size so the width fits on the page.

Graphics like this use up more memory than some browsers get.

Here's the data that you've copied into the *input slot* of a single reporter:
`
TEXT010000010010000001110011011011010110000101110010011101000010000001110000011010000110111101101110011001010010110000100000011011000110100101101011011001010010000001111001011011110111010101110010001000000110110001100001011100000111010001101111011100000010000001101111011100100010000001100100011001010111001101101011011101000110111101110000001000000110001101101111011011010111000001110101011101000110010101110010001011000010000001100011011000010110111000100000011100110111010001101111011100100110010100100000011011100111010101101101011000100110010101110010011100110010110000100000011100000110100101100011011101000111010101110010011001010111001100101100001000000111010001100101011110000111010000101100001000000110110101110101011100110110100101100011001011000010000001100001011011000110110000100000011010110110100101101110011001000111001100100000011011110110011000100000011101000110100001101001011011100110011101110011001011100010000001000010011101010111010000100000011101000110100001100101001000000111101001101001011011000110110001101001011011110110111000100000011011000110111101100011011000010111010001101001011011110110111001110011001000000110100101101110011100110110100101100100011001010010000001101001011101000111001100100000011011010110010101101101011011110111001001111001001000000110010001101111011011100010011101110100001000000110001101101111011011100111010001100001011010010110111000100000011100000110100101100011011101000111010101110010011001010111001100100000011011110111001000100000011001010111011001100101011011100010000001101110011101010110110101100010011001010111001001110011001011100010000001000101011000010110001101101000001000000110110001101111011000110110000101110100011010010110111101101110001000000110100001101111011011000110010001110011001000000110000100100000011000100110100101110100001000000110111101100110001000000111010001101000011000010111010000100000011010010110111001100110011011110111001001101101011000010111010001101001011011110110111000101100001000000110000101110000011100000111001001101111011100000111001001101001011000010111010001100101011011000111100100100000011000110110000101101100011011000110010101100100001000000110000100100000001000100110001001101001011101000010110000100010001000000111011101101000011010010110001101101000001000000110100101110011001000000110101001110101011100110111010000100000001000100100111101101110001000100010000001101111011100100010000000100010010011110110011001100110001011100010001000100000010101000110100001100001011101000010011101110011001000000110000101101100011011000010111000100000010101110110100001100101011011100010000001110111011001010010000001110111011100100110100101110100011001010010110000100000011101110110010100100000011011110110011001110100011001010110111000100000011100110111100101101101011000100110111101101100011010010111101001100101001000000100111101100110011001100010000001100001011100110010000000110000001011000010000001100001011011100110010000100000010011110110111000100000011000010111001100100000001100010010110000100000011000100111010101110100001000000111010001101000011001010010000001101101011001010110110101101111011100100111100100100000011010010111001100100000011011100110111101110100001000000111001101110100011011110111001001101001011011100110011100100000001100000111001100100000011000010110111001100100001000000011000101110011001011100010000001000010011010010111010001110011001000000110000101110010011001010010000001101010011101010111001101110100001000000100111101101110001000000110111101110010001000000100111101100110011001100010111000100000010101110110100001100101011011100010000001110111011001010010000001110100011001010111001101110100001000000110000100100000011000100110100101110100001000000111010001101111001000000111001101100101011001010010000001101001011001100010000001101001011101000010011101110011001000000110111101101110001011000010000001110100011010000110010100100000011101000110010101110011011101000010000001110010011001010111010001110101011100100110111001110011001000000110000100100000010000100110111101101111011011000110010101100001011011100010000001110110011000010110110001110101011001010011101000100000011010010110011000100000011101000110100001100101001000000110001001101001011101000010000001101001011100110010000001001111011011100010110000100000011010010111010000100000011100100110010101110100011101010111001001101110011100110010000001010100011100100111010101100101001000000110010101101100011100110110010100100000010001100110000101101100011100110110010100101100001000000110011001101111011100100010000001110111011010000110100101100011011010000010000001110111011001010010000001100001011011000111001101101111001000000111010101110011011001010010000000110001001000000110000101101110011001000010000000110000001000000110000101101110011001000010000000110001001000000110000101110011001000000110000100100000011000110110111101101110011101100110010101101110011010010110010101101110011101000010000001110011011010000110111101110010011101000110100001100001011011100110010000101110001000000100100101100110001000000111011101100101001000000110001101101111011101010110110001100100001000000111001101100101011001010010000001101001011011100111001101101001011001000110010100100000011101000110100001100101001000000110110101100101011011010110111101110010011110011000000001100101110011001000000110001001101001011101000111001100101100001000000110000101101110011001000010000001101001011001100010000001110111011001010010000001110111011100100110111101110100011001010010000001101001011101000010000001100001011100110010000000110000011100110010000001100001011011100110010000100000001100010111001100101100001000000110000100100000011100110110010101100011011101000110100101101111011011100010000001101111011001100010000001110100011010000110010100100000011011010110010101101101011011110111001001111001001000000110110101101001011001110110100001110100001000000110110001101111011011110110101100100000011100110110111101101101011001010111010001101000011010010110111001100111001000000110110001101001011010110110010100100000011101000110100001101001011100110011101000100000`

Not even Scratch can handle input slots this wide.

To fix: Put the data into a variable and use the variable in the input instead.

I mean, look, ... ah no, forget it.

**Comment by cycomachead** [comment] 2017-10-05 08:09
While I agree this belongs in a variable, that's not really the problem. You have to paste that in at least once, so the weird rendering thing can get in the way.

In terms of usability, the width is mostly a problem that could be solved by line wrapping. 

People can paste these sorts of things in all kinds of places on the web. It's not an unreasonable expectation for it to just work.

**Comment by jmoenig** [comment] 2017-10-05 12:30
You can also import the data directly from a file onto a variable.
Or, you can access it via HTTP.
Another idea is to paste it into a scrolling input field, such as the stage prompter when you ASK something, and then access the ANSWER.

Are we really teaching zeroes and ones now? Whatever happened to "Beauty and Joy". 
Give schools an exciting programming environment and they'll invent binary.

Words cannot express my dismay

**Comment by towerofnix** [comment] 2017-10-05 12:39
> Give schools an exciting programming environment and they'll invent binary.
> Words cannot express my dismay

How is it at all bad for someone to explore a topic that's interesting to them? Isn't that beauty and joy?

But I'm not going to philosophically argue much. In any case, this is *definitely* a bug. Either it should render correctly, or there should be a limit on the input slot's length. Both are solutions, and leaving it as it is is not.

**Comment by jmoenig** [comment] 2017-10-05 12:52
Sure it should render correctly. Complain to Google's Chrome team about it! Snap is just using standard APIs, and there is no way to tell whether Chrome or the graphics card is low on memory.

I do understand that this isn't about binary, but I can't help my strong feelings against exercises like these. IMO as soon as anybody mentions zeros and ones a baby kitten dies.

**Comment by brianharvey** [comment] 2017-10-05 16:31
I totally agree with you about the horrors of binary vs. beauty and joy.  Sadly, we are constrained by the <s>Evil Empire</s> College Board, and they in turn are influenced by the fact that it's _really easy_ to write multiple choice questions about binary.

OTOH nowhere in the framework does it say we have to use 6400-bit numbers.  I'm going to start reviewing that whole unit today, which, to be fair to the kitten-killers, was written by other team members taking up the slack while I, who should have done it, mostly sat around depressed.

**Comment by cycomachead** [comment] 2017-10-05 18:17
To be fair to Chrome team — we are doing things explicitly recommended against in the Canvas spec. None of this was intended. I’m impressed Snap works as well as it does  at times. 

As far as binary: I agree with Brian’s assessment that the size of the number is a bit unnecessary, but binary can be an incredibly  interesting thing. 
It’s mind boggling in a way that we are able to represent literally anything we could imagine with two digits. Understanding binary, opens the way for far more interesting discussions about why quantum computing is a powerful and completely game changing paradigm for what we think of as a computer. 

Arithmetic is pretty stupid, and I don’t really care about learning two’s compliment, but there are some damn interesting things that can be explored through binary. 

Every time we dismiss ideas as good and bad we do a disservice to students who come across them or think they could be interesting. 
-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment] 2017-10-05 18:32
But, Michael, we can't teach everything, and it's not anything profound or awe-inspiring that gives binary its place in the curriculum.  It's just an asymmetry in the input-output curve of a transistor (namely, not having a third quadrant matching the first quadrant) that gives us binary rather than trinary.  And we don't teach that!  Instead we teach how to convert between bases, because (again) it's easy to write test questions about that.  And we seriously confuse both teachers and students about the number/numeral distinction with those conversion algorithms, which ironically elevate _decimal_ to the status of actual numberhood.

Anyway, once you've wrapped your mind around the ability to represent any number using _ten_ digits, is it really so surprising that you can do it in nine digits, or eight, or...?  The surprising thing is that if you want to do it with one digit you have to change the encoding.

I think, although I'm not an expert, that there's a circularity in your argument about quantum computing.  Quantum physics says certain quantities are restricted to discrete values, but not necessarily to two values.  Organizing the technology around the qubit is a result of organizing regular computers around the bit; they could have engineered qutrits or qudecidigits instead.  Binary is useful in computer architecture because it reduces arithmetic to Boolean algebra, but _that's_ not in the AP framework either.  (Boolean operators are, but not the reduction of arithmetic to logic.)

**Comment by cycomachead** [comment] 2017-10-05 19:09
Sure, I agree that binary isn’t like the coolest thing but almost no one considers how we represent data in real life until you get to CS. 

My point about quantum computing, could be a bit circular. I suppose. My point was that I think it’s a bit easier to reason about  a qubit if you already understand some stuff about binary. 


Anyway, Snap! is a platform and a language that should let you explore ideas. We should be enabling people not restricting them by saying something isn’t worth learning. 

Even if we don’t think students should be looking at 64 bit numbers, that’s on curriculum designers. BUT once they do, the goal of Snap! should be to make that exploration work. 

“You can’t do that here” is a huge frustration of so much software. We only have these issues because of implementation decisions which users don't know and don’t care to understand. 

In this case it’s particularly frustrating because the fixes aren’t that hard. We just need word wrapping. This isn’t an issue where the fixes significantly impact something else or make the UI more complex for novices. 
There are legitimate reasons not to support certain things but I don’t think this is a one of those times. 
-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by brianharvey** [comment] 2017-10-05 20:20
Right, I'm not arguing against fixing the software problem, just sympathizing with Jens's view about teaching ones and zeros instead of computer science.  (More background:  Our biggest problem with the curriculum is that teachers complain there isn't time to fit it all in.)

**Comment by cycomachead** [comment] 2017-10-05 20:41
Sure, but that’s a BJC problem.  Teaching binary is a part of CS, so someone’s going to do it. 

Otherwise if we are prioritizing BJC problems, then the things we need in Snap! are different.

**Comment by brianharvey** [comment] 2017-10-05 20:54
In principle we _are_ prioritizing BJC.  Not only does that reflect the interests of the Inner Circle, but BJC students and teachers are by far the biggest part of Snap<i>!</i>'s user base.

In practice, it's more complicated.  Basically each of us puts in enough effort on BJC-related problems so as not to feel guilty about working on OOP or color management or macros or whatever excites each of us personally.  And sometimes (as with Undo) a BJC-related issue is also a pressing universal issue.

But the reason we're having this particular discussion on this particular issue page is that Mary raised a narrowly curricular problem and Jens suggested that maybe it's the curriculum that's really the problem in this specific case.  I think it's uncontroversial to say that handling infinitely wide text would be a good thing, but in the absence of pressure from BJC it'd be pretty low on the bug list.

Honestly, right now, at the very top of my personal bug list is the one about Miosoft sending out password-change emails that instantly expire, just because I'm being barraged by them right now for some reason.

**Comment by cycomachead** [comment] 2017-10-07 05:02
Sorry, I guess the BJC thing was kind of a red herring, not what really gets me. (And similarly defending binary; also a red herring.) Absent BJC, the issues that Mary ran into have been posted multiple times over multiple years. If we want to say "this is a use case we don't care about" -- then just say that. But saying it's a curricular is just blaming the user. (And look at the issues I linked, there's others linked from there.)

What's more frustrating though, is that we know Mary. I know she knows how to use Snap! well, but she keeps running into issues like this. That one means that students and teachers who don't know Snap! are probably going to run into these issues at some point too -- if they haven't already and we just never know about it.  Plus, the errors that happen from this problem are bad, it's not like Snap! is just slow -- it's totally broken. 

> I think it's uncontroversial to say that handling infinitely wide text would be a good thing, but in the absence of pressure from BJC it'd be pretty low on the bug list.

I agree this isn't a totally high priority, but we can say that without being totally dismissive. It's the thing we train teachers and TAs not to do! Yes, stuffing tons of text in an input might seem stupid to some, but when you actually stop and think about the process -- it's not unreasonable. Students' to crazy things all the time, but it's turns out there's a (mostly) logical path that leads to those scenarios. And there are multiple solutions to this problem.

**Comment by brianharvey** [comment] 2017-10-07 19:12
I totally agree with all of that.

The meta-issue as I see it is that we have a _lot_ of bugs, and a fair number of -- I'm not sure what the word is, like "misfeature" but it's a _missing_ feature that's missing on purpose, such as tiny offstage display of sprite and mouse positions as in Scratch.  _All_ of which would be cleared up _in a month_ if Jens got over his aversion to siccing 12-year-olds on the source code.  Jens gets mad when I talk about it (and will get mad about me writing about it), but there's just no way he's going to attack all the problems, and he _shouldn't_ attack them; his time is needed for major advances such as OOP and a better debugger and macros.

So, every once in a while, some particular problem bubbles up, because some privileged user, often but not always BJC-related, happens to make a fuss about it.  Maybe this will turn out to be one of them, such that Jens gets to where he finds the complaints more troublesome than the time spent to fix it.  Or maybe not; I can never predict.

Apart from back end problems, I'd like to see this old idea
![circles1](https://user-images.githubusercontent.com/3885074/31311022-a85daba2-ab71-11e7-8ce2-6f0df362681a.png)
or one of the variants people have proposed implemented.  And/or get rid of the whole concept of empty=0.  It's probably not the most urgent problem we have, but I'm really proud of how we handle anonymous functions and I want it to be perfect.

**Comment by cycomachead** [comment] 2017-10-07 22:14
I would love to separately (and probably privately) talk with everyone about prioritization. Partially so we could eliminate some back and forth all the time, but it would help us. 

That last suggestion strikes me as particularly useful because there’s broad implications for the actual reason Snap! exists: teaching. 

So far all (well most) of our work has focused on the curricular side of things with the implicit help of Snap! but we haven’t really explored new ideas in tools for teaching lately. (IMO). We’ve built plenty of cool things but not really tested any of the ways we think about these topics. 
-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by cycomachead** [comment] 2017-10-07 22:16
To be clear, I’m part of the problem of talking about priorities because I think everything is important. And while we’ve discussed ways to prioritize specific ideas, we’ve never had a framework for the types of issues, or one based on severity. 

(For example, long text shouldn’t break projects, but it doesn’t need to work super well.)

-- 
Michael Ball
From my iPhone
michaelball.co

**Comment by bromagosa** [comment] 2019-06-07 07:24
Closing as duplicate of #20: Large amounts of text cause rendering errors

**Closed by bromagosa** 2019-06-07 07:24 UTC
Labels: bug, morphic
