### ISSUE TITLE
Two different block search interfaces?

### ISSUE THREAD

**Issue by ToonTalk** [jmoenig/Snap#2231] opened 2018-10-23 13:51 UTC
I regularly use control-f but today tried clicking on the block search icon.

![image](https://user-images.githubusercontent.com/2138696/47365128-cae0b380-d6d2-11e8-9032-7975a1435e48.png)

and was surprised that it only displays matching commands while control-f displays reporters and commands. Is this intentional?

**Comment by jmoenig** [comment] 2018-10-23 14:53
hmmm.... the icon is the exact same feature as pressing ctrl-f, for me it displays every match, including reporters and hat blocks. I guess I can't reproduce this...

**Comment by ToonTalk** [comment] 2018-10-23 16:44
With a fresh Snap! I can't reproduce it either. Perhaps it got into some strange state.

But the icon interface consistently causes the first match to be highlighted and control-f doesn't so it isn't exactly the same feature is it?

**Comment by jguille2** [comment] 2018-10-23 18:05
Hi @ToonTalk,

I think you are confused...

The search icon is a _magnifying glass_ and its behavior is the same than _ctrl-f_

But I guess you are talking about the _use the keyboard to enter blocks_ feature (the _keyboard_ icon)

Joan

**Comment by ToonTalk** [comment] 2018-10-24 08:07
Yes I was referring to the keyboard icon as in the image of the original post here.

I've managed to reproduce the problem. It occurs after importing the attached project.

[eCraft2Learn.zip](https://github.com/jmoenig/Snap/files/2509513/eCraft2Learn.zip)

**Comment by jguille2** [comment] 2018-10-24 09:03
Hi!
I don't understand... I don't see any problem

Your original post talked about _the action_ only shows commands (and not reporters). But if you are using the _Keyboard editing_ feature, you will only see the blocks that makes sense in the context you are. Then, if you are building a script and you are attaching a block to other block, only commands will appear in your search.

So, the behavior changes in different contexts (where the white line is).

Joan

**Comment by ToonTalk** [comment] 2018-10-24 09:18
I see now. But the tooltip on the icon says "use the keyboard to enter blocks" which I assumed was identical to typing control-f. But I see now that the icon has a context that control-f doesn't.  Is "entering" blocks different from "finding" blocks? Except it doesn't enter the blocks, it just displays a subset of blocks it thinks I might want to drag in the script area.

Also I don't understand what context means. I just clicked on a command block and then the keyboard icon as if I wanted to add a reporter to one of the arguments but it still didn't give me any reporters.

And I must admit I thought that the white line was a bug -- in any case I imagine it is mysterious to most users.

**Comment by jguille2** [comment] 2018-10-24 09:57
Hi!
This feature can be improved, of course, but I think it's quite coherent.

"Use the keyboard to enter blocks" does not mean "search". Searching is for "drag and drop" (with the mouse!). 

The "context" is where you are scripting. You can use the arrows, and the "white line" move you across the scripts. Up and Down and also Left and Right (going inside, to the slots) and Tab (moving to other scripts) .

To see this clearer

![keyboardediting1](https://user-images.githubusercontent.com/2926315/47422871-f96a9700-d783-11e8-94ed-622b315e54ba.png)

![keyboardediting2](https://user-images.githubusercontent.com/2926315/47422888-fff90e80-d783-11e8-9fa9-b82512964b30.png)

**Closed** 2018-10-24 10:54 UTC

**Comment by DyslexicAwe** [comment] 2018-10-26 07:53
> I regularly use control-f but today tried clicking on the `block search icon`.
> 
> ![image](https://user-images.githubusercontent.com/2138696/47365128-cae0b380-d6d2-11e8-9032-7975a1435e48.png)

I think other users, including me, are/were (and/or probably will be) as confused as ToonTalk  and because of that I think - the explanation and pictures (provided by @jguille2) would be appreciated if  included in next version of the Manual. 

If you @ToonTalk wouldn't mind editing your initial question (as shown below), I think it would make clearer the topic of this discussion. 
![searchvskeyboard](https://user-images.githubusercontent.com/16387241/47552392-dc110680-d904-11e8-9e5f-d03db742a1d5.png)
