### ISSUE TITLE
Hidden sprite still collides with other sprites

### ISSUE THREAD

**Issue by nickedens** [jmoenig/Snap#1468] opened 2016-10-20 20:48 UTC
I run a local non profit group that teaches kids 8-18 how to code. We have been using scratch for the past year for our beginner game programming classes. However after playing around with Snap I much prefer it across the board with features and speed. I also really like the fact we can export the students final projects as exe games they can share with friends. 

The kids make a spaceship shooting game where a ship flies around shooting bad ships and collecting powerups. Having said all of that the sticking point with Snap is when we hide a master sprite and then generate clones of the master in the game the master hidden sprite still detects collision. 

Our use case is this:

We have an enemy ship and hide the ship on program start. The user walks through a start screen and a getting ready screen. Once level 1 starts we clone the master ship and randomly place it on the stage. Every time the ship is destroyed we wait for x seconds and clone another copy from the master. This works perfectly in Scratch as collision is not detected with our "hidden" master enemy ship. Unfortunately running that same code in Snap results in our player ship running into the hidden master enemy copy and killing the player ship. 

I assume this is a bug but if it is indeed a feature of Snap is there a way then to remove/hide the master sprite used for clones completely so collision doesn't take effect on them?

I can make up our use example and upload it if needed.

**Comment by bromagosa** [comment] 2016-10-21 15:54
I have no idea whether it's a bug or an intended behavior, but you could try moving the sprite outside the Stage area (`[ go to (9999) (9999)]`, for instance).

**Comment by nickedens** [comment] 2016-10-27 17:12
Yeah. I guess that would work. When we do bullets for the ships we hide the master bullet sprite but setup the code so it tracks the ship. When the fire button is pressed it just clones itself, shows, and moves in whatever direction it is currently in. Is there no chance of getting this fixed or at least an alternative created? Based on the games the kids make it will require a considerably different approach that, although would work, is probably more difficult to grasp. We would have to keep the master off screen, and on fire button press clone the bullets, move them to the ship and rotate them to place, then show and move them. So doable but I guess not as straight forward.

**Comment by brianharvey** [comment] 2016-10-27 17:39
I agree that what you want to do is very reasonable.  Sadly, I can also think of use cases the other way, so probably we'll eventually make this settable.  (I can hear Jens disagreeing already...)

**Comment by nickedens** [comment] 2016-10-27 17:50
Or even if we had a block so I could detect if the sprite was visible, meaning the show block was used to show the sprite, that would fix my issue as we could detect that on collision detection. That would totally work and not interfere with what your current users may use that block for.

**Comment by brianharvey** [comment] 2016-10-27 18:02
Here you go:
[visible.xml.zip](https://github.com/jmoenig/Snap--Build-Your-Own-Blocks/files/556637/visible.xml.zip)

**Comment by nickedens** [comment] 2016-10-27 18:08
ok. thats sweet. That will get what I want. Thanks!

**Comment by jmoenig** [comment] 2019-06-03 15:20
This has now been implemented and the issue has been resolved. Thank you! Closing...

**Closed by jmoenig** 2019-06-03 15:20 UTC
Labels: cat: sensing, question
