### ISSUE TITLE
an annoying bug in list

### ISSUE THREAD

**Issue by gego51** [jmoenig/Snap#2791] opened 2021-03-01 13:40 UTC
I found a bug in my project with the lists
when I replace a list item in an array, items around it are also changed
please try with my project https://snap.berkeley.edu/project?user=gego51&project=copperfield%20
1 read the project and after the menu and move the catactere in a surface, the bug don't run in water
2 stop the project
3 in the editor, click to the red block with "wood"
4 restart game
5 look the result

I have post this in the forun

**Comment by jmoenig** [comment] 2021-03-01 13:49
Can you be a little bit more specific or help me narrow down what you're expecting vs. what's happening?

It's *very* unlikely that mutating one list also mutates another one except when both are sharing the same elements, e.g. the same sublist.

**Comment by gego51** [comment] 2021-03-01 14:00
I try to made a Minecraft clone game, so i use lists inner a list (an array) for the two dimentional world, in each occurrence of the array, I use a 3rd list (a list in the array) to generate the layer levels (the back, middle and front), the bugue is done when I modify this list, lists of other occurence of the array are also changed while have modified only one, and this bug also appears when the project is stopped

**Comment by gego51** [comment] 2021-03-01 14:35
this bug run when the last item of a list inside an array is empty

**Comment by jmoenig** [comment] 2021-03-01 18:17
apparently this has been solved in the forums now, and determined to be caused by using identical lists in several places, https://forum.snap.berkeley.edu/t/an-annoying-bug/5657/8
Since it's not a Snap! bug, I'm closing this issue now.

**Closed by jmoenig** 2021-03-01 18:17 UTC
